### ISSUE TITLE
Version 1.0.7 is invalid

### ISSUE THREAD

**Issue by renatorib** [ctrlplusb/react-component-queries#60]
If you install this version anywhere, you will see that have no lib folder.
It seems version 1.0.7 has published to npm without build it.

**Comment by ctrlplusb** [comment]
Wow! Hmmm I will check the Travis CI build. Thanks for the heads up!

**Comment by renatorib** [comment]
You're welcome :)

**Comment by ctrlplusb** [comment]
New release 1.0.8

Thanks again!
