### ISSUE TITLE
SSR issues resolved?

### ISSUE THREAD

**Issue by loganpowell** [ctrlplusb/react-component-queries#90]
Great work on making modularity a reality in React! Does this library resolve the SSR issues with sizeme in any way?

**Comment by ctrlplusb** [comment]
Hey @loganpowell, thanks! 

Unfortunately not.  It will suffer much of the same issues as described on react-sizeme.  If you plan to use it within SSR you could equally set the `noPlaceholder` configuration value in order to ensure that you get something rendered.
